### ISSUE TITLE
Any usage or use case with this and unity3d?

### ISSUE THREAD

**Issue by herbertmilhomme** [Ellpeck/Coroutine#18]
I have some ideas of how it could be used... but not sure if there are any actual tests done with this inside a unity project. Are they compatible? Are there any pitfalls and quirks to be noted of? Would you recommend it? Should i approach it from a specific design style/pattern? etc... The project is very small and simple, but exploring the use of it is very limited. It's hard to tell full scope of potential or practicality. Maybe i could be over thinking things... but who knows.

**Comment by Ellpeck** [comment]
Coroutine is very heavily based on Unity's [existing coroutines](https://docs.unity3d.com/Manual/Coroutines.html), but it contains a few extra features, like the ability to wait for specific events. 

If you don't need those extra features, sticking with Unity's default version probably makes more sense.
