### ISSUE TITLE
Is it possible to run few coroutines in one (e.g. foreground) thread and few in the (e.g. background) other

### ISSUE THREAD

**Issue by zaafar** [Ellpeck/Coroutine#2]

**Comment by Ellpeck** [comment]
Behavior like this isn't currently possible. 

This can easily be achieved by building a modified version yourself. All you have to do is make all of the methods in `CoroutineHandler` non-static. Then, you can create separate instances that run on different threads.

**Comment by zaafar** [comment]
thanks!!
