### ISSUE TITLE
[Feature Request] [Co-routine Stats] A co-routine saves average time it take to execute MoveNext()

### ISSUE THREAD

**Issue by zaafar** [Ellpeck/Coroutine#4]
Thank you for the amazing library! In my project I am trying to create a **debug ui** which shows the following.

* Total number of co-routines running in an application.
** Total event based
** Total time based
* Name of each co-routines (this is optional)
* Time taken by each co-routine's MoveNext() function.

NOTE: (optional)) In case a coroutine calls RaiseEvent() function to trigger a new coroutine, the time taken by the new coroutine shouldn't be counted in the current coroutine, it should be counted in the newly triggered coroutine.

Do you think such functionality have a place in this library? If I implement such functionality, how open would you be in accepting it into this library?

**Comment by Ellpeck** [comment]
I can add some of these features myself in a later update!

**Comment by zaafar** [comment]
Thx for doing this, I will test it out over the weekend!
